#!/bin/bash
# Quick Reference - Common Commands

echo "🎬 SORA VIDEO SCRAPER - Quick Reference"
echo "========================================"
echo ""
echo "📥 VIDEO SCRAPING:"
echo "  Single URL (10 remixes):"
echo "    python main.py https://sora.chatgpt.com/p/VIDEO_ID --max 10"
echo ""
echo "  With existing Chrome:"
echo "    python main.py https://sora.chatgpt.com/p/VIDEO_ID --use-existing --max 50"
echo ""
echo "  Batch processing:"
echo "    python main.py --batch urls.txt --max 50 --slow --use-existing --output batch-1"
echo ""
echo "  Metadata only (no videos):"
echo "    python main.py https://sora.chatgpt.com/p/VIDEO_ID --metadata-only --max 20"
echo ""
echo "📺 YOUTUBE UPLOADER:"
echo "  One-time upload:"
echo "    python -m src.youtube_uploader.uploader --source videos/to-upload --dest videos/uploaded"
echo ""
echo "  Watch mode (continuous):"
echo "    python -m src.youtube_uploader.uploader --source videos/to-upload --dest videos/uploaded --watch"
echo ""
echo "  With custom privacy:"
echo "    python -m src.youtube_uploader.uploader --source videos/to-upload --dest videos/uploaded --watch --privacy unlisted"
echo ""
echo "📁 PROJECT STRUCTURE:"
echo "  main.py              - Main entry point"
echo "  src/scraper/         - Video scraping code"
echo "  src/youtube_uploader/ - YouTube upload code"
echo "  tests/               - Test files"
echo "  docs/                - Documentation"
echo ""
echo "📚 DOCUMENTATION:"
echo "  README.md                     - Main readme"
echo "  docs/YOUTUBE_UPLOADER.md      - YouTube guide"
echo "  docs/BATCH_PROCESSING.md      - Batch processing"
echo "  docs/QUICKSTART.md            - Quick start"
echo ""
echo "For more help:"
echo "  python main.py --help"
echo "  python -m src.youtube_uploader.uploader --help"
